### ISSUE TITLE
Error running name node

### ISSUE THREAD

**Issue by jacobtomlinson** [GELOG/docker-ubuntu-hadoop#30]
The first instruction in the README results in:

```
2016-02-18 10:04:41,281 WARN  [main] common.Storage (Storage.java:analyzeStorage(477)) - Storage directory /data/dfs/name does not exist
2016-02-18 10:04:41,282 WARN  [main] namenode.FSNamesystem (FSNamesystem.java:loadFromDisk(741)) - Encountered exception loading fsimage
org.apache.hadoop.hdfs.server.common.InconsistentFSStateException: Directory /data/dfs/name is in an inconsistent state: storage directory does not exist or is not accessible.
    at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverStorageDirs(FSImage.java:313)
    at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverTransitionRead(FSImage.java:202)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFSImage(FSNamesystem.java:1020)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFromDisk(FSNamesystem.java:739)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.loadNamesystem(NameNode.java:536)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:595)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:762)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:746)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1438)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1504)
2016-02-18 10:04:41,285 INFO  [main] mortbay.log (Slf4jLog.java:info(67)) - Stopped HttpServer2$SelectChannelConnectorWithSafeStartup@0.0.0.0:50070
2016-02-18 10:04:41,385 INFO  [main] impl.MetricsSystemImpl (MetricsSystemImpl.java:stop(210)) - Stopping NameNode metrics system...
2016-02-18 10:04:41,386 INFO  [main] impl.MetricsSystemImpl (MetricsSystemImpl.java:stop(216)) - NameNode metrics system stopped.
2016-02-18 10:04:41,386 INFO  [main] impl.MetricsSystemImpl (MetricsSystemImpl.java:shutdown(605)) - NameNode metrics system shutdown complete.
2016-02-18 10:04:41,386 FATAL [main] namenode.NameNode (NameNode.java:main(1509)) - Failed to start namenode.
org.apache.hadoop.hdfs.server.common.InconsistentFSStateException: Directory /data/dfs/name is in an inconsistent state: storage directory does not exist or is not accessible.
    at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverStorageDirs(FSImage.java:313)
    at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverTransitionRead(FSImage.java:202)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFSImage(FSNamesystem.java:1020)
    at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFromDisk(FSNamesystem.java:739)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.loadNamesystem(NameNode.java:536)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:595)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:762)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:746)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1438)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1504)
2016-02-18 10:04:41,387 INFO  [main] util.ExitUtil (ExitUtil.java:terminate(124)) - Exiting with status 1
2016-02-18 10:04:41,388 INFO  [Thread-1] namenode.NameNode (StringUtils.java:run(659)) - SHUTDOWN_MSG:
/************************************************************
SHUTDOWN_MSG: Shutting down NameNode at hdfs-namenode/172.17.0.2
************************************************************/
```

**Comment by mikefaille** [comment]
I just tried on my side for Hadoop 2.6.0 using theses commands : 
- dockebuild -t  gelog/hadoop  .
- docker run -d --name hdfs-namenode     -h hdfs-namenode -p 50070:50070     gelog/hadoop hdfs namenode && docker logs -f hdfs-namenode

@jacobtomlinson  How can we reproduce your issue ?

**Comment by jacobtomlinson** [comment]
From a fresh install of docker on an ec2 instance I just ran

```
docker run -d --name hdfs-namenode \
    -h hdfs-namenode -p 50070:50070 \
    gelog/hadoop hdfs namenode && \
docker logs -f hdfs-namenode
```

However I've now added the following after formatting the hdfs namenode

```
RUN mkdir  -p /data/dfs/data /data/dfs/name /data/dfs/namesecondary
```

and it now works for me.

**Comment by mikefaille** [comment]
Thank you mister. I suggest you to create a pull request.

Can you share your Docker version too ?

---

Michaël

**Comment by jacobtomlinson** [comment]
Docker version 1.9.1
Docker Compose version 1.6.0, build d99cad6
